version: '2'
services:
    automation-app:
        container_name: practera-ruby-automation-chrome
        image: practera/automation-chrome:latest
        environment:
           - MODE=hub
           - UPLOAD_FILE_PATH=/app/uploadFile
           - HUB_URL=http://192.168.1.5:10009
           - NODE_BROWSER_VERSION=71
           - NODE_PLATFORM=MAC
        ports:
           - "127.0.0.1:10009-10010:10009-10010"
        volumes:
           - .:/app